# Generated by Django 4.2.9 on 2024-01-21 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elitenovauser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="elitenovauser",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="elitenovauser",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="elitenovauser",
            name="user_permissions",
        ),
    ]
