# Generated by Django 4.2.9 on 2024-01-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0002_remove_elitenovauser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="elitenovauser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
