# Generated by Django 4.2.9 on 2024-01-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0004_alter_elitenovauser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elitenovauser",
            name="employee_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
