# Generated by Django 4.2.9 on 2024-01-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0006_elitenovauser_plain_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drawer",
            fields=[
                ("drawer_id", models.AutoField(primary_key=True, serialize=False)),
                ("drawer_type", models.CharField(max_length=255)),
                ("drawer_code", models.CharField(max_length=255)),
            ],
        ),
    ]
