# Generated by Django 4.2.9 on 2024-01-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0009_alter_colorknob_colorknob_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnobModel",
            fields=[
                ("knob_id", models.AutoField(primary_key=True, serialize=False)),
                ("knob_family", models.TextField()),
                ("knob_model", models.TextField()),
                ("two_parts_knob", models.IntegerField()),
                ("color", models.IntegerField()),
                ("knob_size", models.FloatField()),
                ("button_height", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="colorknob",
            name="colorknob_description",
            field=models.TextField(),
        ),
    ]
