# Generated by Django 4.2.9 on 2024-01-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0011_rename_knobmodel_knob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("collection_id", models.AutoField(primary_key=True, serialize=False)),
                ("collection_name", models.CharField(max_length=255)),
                ("collection_barcode", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("back", models.TextField()),
                ("kant", models.TextField()),
                ("min_order", models.IntegerField()),
                ("in_stock", models.IntegerField()),
                ("flow", models.CharField(max_length=255)),
                ("height", models.FloatField()),
                ("width", models.FloatField()),
                ("kant_code", models.TextField()),
                ("formica", models.CharField(max_length=255)),
            ],
        ),
    ]
