# Generated by Django 4.2.9 on 2024-01-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0012_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="formica",
            field=models.IntegerField(),
        ),
    ]
