# Generated by Django 4.2.9 on 2024-01-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0014_collection_created_at_collection_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="flow",
            field=models.IntegerField(),
        ),
    ]
