# Generated by Django 4.2.9 on 2024-01-27 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0015_alter_collection_flow"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTrack",
            fields=[
                ("order_track_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_id", models.BigIntegerField()),
                ("order_status", models.CharField(default="draft", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
