# Generated by Django 4.2.9 on 2024-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0018_helpertables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elitenovauser",
            name="username",
            field=models.CharField(default="custom", max_length=255),
        ),
    ]
