# Generated by Django 4.2.9 on 2024-01-29 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0020_alter_elitenovauser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helpertables",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="helpertables",
            name="updated_at",
        ),
    ]
