# Generated by Django 4.2.9 on 2024-01-31 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0021_remove_helpertables_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertrack",
            name="order_cards_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ordertrack",
            name="order_collection_entries_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ordertrack",
            name="order_decision_tracker",
            field=models.CharField(default="no", max_length=10),
        ),
        migrations.CreateModel(
            name="OrderItems",
            fields=[
                ("order_item_id", models.AutoField(primary_key=True, serialize=False)),
                ("order_item_collection_barcode", models.TextField()),
                ("order_item_collection", models.TextField()),
                ("order_item_keepflow", models.TextField()),
                ("order_item_texture", models.TextField()),
                (
                    "order_item_uploaded_img",
                    models.ImageField(upload_to="uploaded_images/"),
                ),
                ("order_item_knobfamily", models.TextField()),
                ("order_item_knobcolor", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.ordertrack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HingeOrder",
            fields=[
                ("hinge_order_id", models.AutoField(primary_key=True, serialize=False)),
                ("hinge_order_provider", models.IntegerField()),
                ("hinge_order_door_opening_side", models.TextField()),
                ("hinge_order_dty", models.TextField()),
                ("hinge_order_yp", models.TextField()),
                ("hinge_order_xp1", models.TextField()),
                ("hinge_order_xp2", models.TextField()),
                ("hinge_order_xp3", models.TextField()),
                ("hinge_order_xp4", models.TextField()),
                ("hinge_order_xp5", models.TextField()),
                ("hinge_order_xp6", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.ordertrack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrawarOrder",
            fields=[
                (
                    "drawar_order_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("drawar_order_type", models.TextField()),
                ("drawar_order_code", models.TextField()),
                ("drawar_order_lo", models.TextField()),
                ("drawar_order_ro", models.TextField()),
                ("drawar_order_bo", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.ordertrack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClapOrder",
            fields=[
                ("clap_order_id", models.AutoField(primary_key=True, serialize=False)),
                ("clap_claps_pr", models.TextField()),
                ("clap_order_lo", models.TextField()),
                ("clap_order_ro", models.TextField()),
                ("clap_order_bo", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.ordertrack",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cards",
            fields=[
                ("card_order_id", models.AutoField(primary_key=True, serialize=False)),
                ("collection_barcode_id", models.CharField(default="", max_length=10)),
                ("card_width", models.IntegerField()),
                ("card_height", models.IntegerField()),
                ("card_quantity", models.IntegerField()),
                ("knob_position_id", models.IntegerField()),
                ("card_notes", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clap_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.claporder",
                    ),
                ),
                (
                    "drawer_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.drawarorder",
                    ),
                ),
                (
                    "hinge_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.hingeorder",
                    ),
                ),
                (
                    "knob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.knob",
                    ),
                ),
                (
                    "order_track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="super_admin.ordertrack",
                    ),
                ),
            ],
        ),
    ]
