# Generated by Django 4.2.9 on 2024-01-31 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0022_ordertrack_order_cards_rows_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="helpertables",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="helpertables",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
