# Generated by Django 4.2.9 on 2024-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0023_helpertables_created_at_helpertables_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cards",
            name="clap_order",
        ),
        migrations.RemoveField(
            model_name="cards",
            name="drawer_order",
        ),
        migrations.RemoveField(
            model_name="cards",
            name="hinge_order",
        ),
        migrations.AddField(
            model_name="cards",
            name="have_clap",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cards",
            name="have_drawer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cards",
            name="have_hinge",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cards",
            name="unique_identifier",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="claporder",
            name="unique_identifier",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="drawarorder",
            name="unique_identifier",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="hingeorder",
            name="unique_identifier",
            field=models.TextField(default=""),
        ),
    ]
