# Generated by Django 4.2.9 on 2024-02-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "super_admin",
            "0024_remove_cards_clap_order_remove_cards_drawer_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="hingeorder",
            name="hinge_order_provider",
            field=models.TextField(),
        ),
    ]
