# Generated by Django 4.2.9 on 2024-02-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0025_alter_hingeorder_hinge_order_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordertrack",
            name="type_of_reservation",
            field=models.TextField(default="new", max_length=20),
        ),
    ]
