# Generated by Django 4.2.9 on 2024-02-15 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0028_ordertrack_order_type_ordertrack_related_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordertrack",
            old_name="order_type",
            new_name="product_type",
        ),
    ]
