# Generated by Django 4.2.9 on 2024-02-23 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0030_alter_elitenovauser_phone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="elitenovauser",
            name="employee_id",
        ),
    ]
