# Generated by Django 4.2.9 on 2024-02-24 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0031_remove_elitenovauser_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelatedOrders",
            fields=[
                (
                    "related_order_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_current_orders",
                        to="super_admin.ordertrack",
                    ),
                ),
                (
                    "past_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_past_orders",
                        to="super_admin.ordertrack",
                    ),
                ),
            ],
        ),
    ]
