# Generated by Django 4.2.9 on 2024-02-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0032_relatedorders"),
    ]

    operations = [
        migrations.AddField(
            model_name="colorknob",
            name="colorknob_color",
            field=models.IntegerField(default=0),
        ),
    ]
