# Generated by Django 4.2.9 on 2024-03-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0033_colorknob_colorknob_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cards",
            name="card_height",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="cards",
            name="card_width",
            field=models.FloatField(),
        ),
    ]
