# Generated by Django 4.2.9 on 2024-03-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0034_alter_cards_card_height_alter_cards_card_width"),
    ]

    operations = [
        migrations.AddField(
            model_name="elitenovauser",
            name="employee_id",
            field=models.CharField(default="", max_length=255),
        ),
    ]
