# Generated by Django 4.2.9 on 2024-03-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0035_elitenovauser_employee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translations",
            fields=[
                ("translation_id", models.AutoField(primary_key=True, serialize=False)),
                ("translation_page_name", models.TextField()),
                ("translation_english_verion", models.TextField()),
                ("translation_hebrew_verion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="elitenovauser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
