# Generated by Django 4.2.9 on 2024-03-22 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0036_translations_alter_elitenovauser_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertrack",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AlterField(
            model_name="ordertrack",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
