# Generated by Django 4.2.9 on 2024-03-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0038_alter_ordertrack_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertrack",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ordertrack",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
