# Generated by Django 4.2.9 on 2024-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0040_alter_cards_knob_alter_ordertrack_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cards",
            name="knob",
            field=models.TextField(default=""),
        ),
    ]
