# Generated by Django 4.2.9 on 2024-03-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("super_admin", "0044_alter_cards_knob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cards",
            name="knob_position_id",
            field=models.TextField(default=""),
        ),
    ]
